services:
  backend:
    build: ./server
    environment:
      - ATLAS_URI=mongodb://mongo:27017/employees
      - PORT=5000
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"   # Backend exposed on host port 5000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  frontend:
    build: ./client
    depends_on:
      - backend
    ports:
      - "3000:3000"     
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  reverse-proxy:
    build: ./nginx
    depends_on:
      - frontend
    ports:
      - "80:80"       
      - "443:443"     
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
