# -*- coding: utf-8 -*-
"""Copy of lora_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qTmgZwY3fwNfweZY-MtjN8YLTUTGNhdq

##  Step 1: Install Dependencies
"""

!pip install -q \
  torch \
  transformers \
  datasets \
  peft \
  bitsandbytes \
  accelerate \
  trl

MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files={
        "train": "train.jsonl",
        "validation": "val.jsonl"
    }
)

dataset

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True
)
tokenizer.pad_token = tokenizer.eos_token

MAX_LENGTH = 512

def format_instruction(example):
    if example["input"].strip():
        prompt = f"""### Instruction:
{example['instruction']}

### Input:
{example['input']}

### Response:
"""
    else:
        prompt = f"""### Instruction:
{example['instruction']}

### Response:
"""

    full_text = prompt + example["output"]

    tokenized = tokenizer(
        full_text,
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH
    )

    response_start = len(
        tokenizer(prompt, add_special_tokens=False)["input_ids"]
    )

    labels = [-100] * response_start + tokenized["input_ids"][response_start:]
    labels = labels[:MAX_LENGTH]

    tokenized["labels"] = labels
    return tokenized

tokenized_ds = dataset.map(
    format_instruction,
    remove_columns=dataset["train"].column_names,
    batched=False
)

import torch
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto"
)

model.config.use_cache = False

from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

"""## 🔹 Step 8: Configure LoRA"""

model.gradient_checkpointing_enable()

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    num_train_epochs=3,
    logging_steps=10,
    save_steps=500,
    eval_strategy="steps",
    save_strategy="epoch",
    eval_steps=500,
    fp16=True,
    optim="paged_adamw_8bit",
    report_to="none"
)

"""## 🚀 Step 10: Initialize Trainer"""

from transformers import Trainer, DataCollatorForLanguageModeling

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["validation"],
    processing_class=tokenizer,
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    )
)

trainer.train()

"""## 🎓 Step 11: Train the Model"""

adapter_path = "./adapters"
model.save_pretrained(adapter_path)
tokenizer.save_pretrained(adapter_path)

from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    quantization_config=bnb_config
)

model = PeftModel.from_pretrained(base_model, adapter_path)
prompt = """### Instruction:
Answer the medical question accurately.

### Input:
What is the outlook for Lip and Oral Cavity Cancer ?
### Response:
"""
inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.6,
        top_p=0.9,
        do_sample=True,
        repetition_penalty=1.1,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id
    )

decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
response = decoded.split("### Response:")[-1].strip()

print("\n" + "=" * 80)
print("MODEL RESPONSE")
print("=" * 80)
print(response)
print("=" * 80)

MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
ADAPTER_PATH = "./adapters"
MERGED_PATH = "./quantized/fp16-merged"

from peft import PeftModel
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    dtype=torch.float16,
    device_map="auto"
)

model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model = model.merge_and_unload()

model.save_pretrained(MERGED_PATH)
tokenizer.save_pretrained(MERGED_PATH)

from transformers import BitsAndBytesConfig

int8_config = BitsAndBytesConfig(
    load_in_8bit=True
)

model_int8 = AutoModelForCausalLM.from_pretrained(
    MERGED_PATH,
    device_map="auto",
    quantization_config=int8_config
)

model_int8.save_pretrained("./quantized/model-int8")
tokenizer.save_pretrained("./quantized/model-int8")

int4_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

model_int4 = AutoModelForCausalLM.from_pretrained(
    MERGED_PATH,
    device_map="auto",
    quantization_config=int4_config
)

model_int4.save_pretrained("./quantized/model-int4")
tokenizer.save_pretrained("./quantized/model-int4")

!python llama.cpp/convert_hf_to_gguf.py \
  ./quantized/fp16-merged \
  --outfile ./quantized/model-fp16.gguf

./build/bin/quantize \
  ../quantized/model.gguf \
  ../quantized/model-q4_0.gguf \
  q4_0

! llama.cpp/build/bin/llama-quantize \
  ./quantized/model-fp16.gguf \
  ./quantized/model.gguf \
  q4_0

! llama.cpp/build/bin/llama-cli \
  -m ./quantized/model.gguf \
  -p "Explain gradient checkpointing in simple terms." \
  -n 128

from datasets import load_dataset

val_ds = load_dataset(
    "json",
    data_files="val.jsonl"
)["train"]

sample = val_ds[1]

instruction = sample["instruction"]
input_text = sample["input"]

def build_prompt(instruction, input_text):
    if input_text.strip():
        return f"""### Instruction:
{instruction}

### Input:
{input_text}

### Response:
"""
    else:
        return f"""### Instruction:
{instruction}

### Response:
"""

prompt = build_prompt(instruction, input_text)
print(prompt)

import time
import torch

def measure_speed(model, tokenizer, prompt, max_new_tokens=100, runs=3):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    # warmup
    with torch.no_grad():
        model.generate(**inputs, max_new_tokens=20)

    times = []
    for _ in range(runs):
        start = time.time()
        with torch.no_grad():
            model.generate(**inputs, max_new_tokens=max_new_tokens)
        end = time.time()
        times.append(end - start)

    avg_time = sum(times) / len(times)
    return max_new_tokens / avg_time  # tokens/sec

# FP16 merged model
model_fp16 = AutoModelForCausalLM.from_pretrained(
    "./quantized/fp16-merged",
    dtype=torch.float16,
    device_map="auto"
)

# INT8 model
model_int8 = AutoModelForCausalLM.from_pretrained(
    "./quantized/model-int8",
    device_map="auto"
)

# INT4 model
model_int4 = AutoModelForCausalLM.from_pretrained(
    "./quantized/model-int4",
    device_map="auto"
)

speed_fp16 = measure_speed(model_fp16, tokenizer, prompt)
speed_int8 = measure_speed(model_int8, tokenizer, prompt)
speed_int4 = measure_speed(model_int4, tokenizer, prompt)


print("FP16:", speed_fp16)
print("INT8:", speed_int8)
print("INT4:", speed_int4)

! llama.cpp/./build/bin/llama-cli \
  -m quantized/model.gguf \
  -p f"{prompt}"\
  -n 100

!pip install torch transformers peft accelerate psutil llama-cpp-python sentence-transformers pandas -q

GGUF_MODEL = "./quantized/model.gguf"
PROMPTS = [
    """### Instruction:
Answer the medical question accurately.

### Input:
What are the treatments for Heart Attack ?

### Response:
""",

    """### Instruction:
Answer the medical question accurately.

### Input:
What is (are) Low Vision ?

### Response:
""",

    """### Instruction:
Answer the medical question accurately.

### Input:
Is Ovarian Epithelial, Fallopian Tube, and Primary Peritoneal Cancer inherited ?

### Response:
"""
]


GROUND_TRUTH = [
    "Heart attack treatment focuses on quickly restoring blood flow using thrombolytic drugs or angioplasty, followed by cardiac rehabilitation, lifestyle changes, and medications to prevent further damage.",

    "People with low vision can receive support services such as vision rehabilitation, counseling, recreation programs, and job training through community and state agencies for the visually impaired.",

    "About 20% of ovarian, fallopian tube, and primary peritoneal cancers are caused by inherited gene mutations, often associated with breast or colon cancer, and genetic testing is recommended for high-risk families."
]

from sentence_transformers import SentenceTransformer
embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

def get_vram():
    if torch.cuda.is_available():
        return torch.cuda.memory_allocated() / 1024**2
    return 0

def accuracy(preds, refs):
    p_emb = embedder.encode(preds, convert_to_tensor=True)
    r_emb = embedder.encode(refs, convert_to_tensor=True)

    sims = util.cos_sim(p_emb, r_emb)

    per_sample_scores = sims.diag().cpu().numpy()

    # for i, score in enumerate(per_sample_scores):
    #     print(f"Sample {i+1} Similarity: {score:.3f}")

    mean_score = per_sample_scores.mean()

    return mean_score

import time
import torch
import psutil
import pandas as pd
from llama_cpp import Llama
from sentence_transformers import SentenceTransformer, util

def benchmark_gguf(label):
    llm = Llama(model_path=GGUF_MODEL, n_ctx=2048, n_threads=8, verbose=False)

    outputs = []
    start = time.time()

    for p in PROMPTS:
        response = ""
        stream = llm(p, max_tokens=256, stream=True)

        for output in stream:
            token = output["choices"][0]["text"]
            response += token
            # print(token, end="", flush=True)

        # print("\n \n")
        outputs.append(response)

    end = time.time()

    tokens = sum(len(o.split()) for o in outputs)
    tps = tokens / (end - start)
    acc = accuracy(outputs, GROUND_TRUTH)

    return {
        "Model": label,
        "Tokens/sec": round(tps, 2),
        "Latency(s)": round(end - start, 2),
        "VRAM(MB)": 0,
        "Accuracy": round(acc, 3)
    }

results = []

results.append(benchmark_gguf("GGUF Q4 llama.cpp"))

from transformers import AutoTokenizer, AutoModelForCausalLM, TextIteratorStreamer

import threading

BASE_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
FT_MODEL = "./quantized/fp16-merged"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
RESULTS_PATH = "results.csv"



def benchmark_hf(model_path, label):

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForCausalLM.from_pretrained(model_path, device_map=DEVICE)

    outputs = []
    start = time.time()

    for prompt in PROMPTS:
        streamer = TextIteratorStreamer(tokenizer, skip_special_tokens=True)
        inputs = tokenizer(prompt, return_tensors="pt").to(DEVICE)

        generation_kwargs = dict(
            **inputs,
            max_new_tokens=256,
            streamer=streamer,
            pad_token_id=tokenizer.eos_token_id
        )

        thread = threading.Thread(target=model.generate, kwargs=generation_kwargs)
        thread.start()

        response = ""
        for token in streamer:
            response += token
        #     print(token, end="", flush=True)

        # print("\n \n")
        outputs.append(response)
        thread.join()

    end = time.time()

    total_tokens = sum(len(tokenizer.encode(r)) for r in outputs)
    duration = end - start
    tps = total_tokens / duration
    acc = accuracy(outputs, GROUND_TRUTH)

    return {
        "Model": label,
        "Tokens/sec": round(tps, 2),
        "Latency(s)": round(duration, 2),
        "VRAM(MB)": round(get_vram(), 2),
        "Accuracy": round(acc, 3)
    }


results.append(benchmark_hf(BASE_MODEL, "Base Model"))
results.append(benchmark_hf(FT_MODEL, "Fine-tuned"))

df = pd.DataFrame(results)
df.to_csv(RESULTS_PATH, index=False)

print(df)

import json

path = "lora_train.ipynb"

with open(path, "r") as f:
    nb = json.load(f)

nb["metadata"].pop("widgets", None)

with open(path, "w") as f:
    json.dump(nb, f, indent=1)